#!/usr/bin/env bash
set -u
cd -- "$(dirname -- "$0")/.." || exit 1
failures=0
pass(){ printf '[PASS] %s\n' "$1"; }
fail_test(){ printf '[FAIL] %s\n' "$1" >&2; failures=$((failures+1)); }

if grep -Eq 'SWITCHER_RELEASE="leap16-r(2[7-9]|[3-9][0-9])"' bootloader-switcher.sh \
 && awk '/leap16_r26.sh/{a=NR} /leap16_r27.sh/{b=NR} /leap16_r28.sh/{c=NR} END{exit !(a&&b&&a<b&&(!c||b<c))}' bootloader-switcher.sh; then
  pass 'r27 layer remains in valid release/load order'
else
  fail_test 'r27 layer release/load order is wrong'
fi

if ! grep -Fq '### This kernel entry is generated by the openSUSE Leap adapter for CachyOS r47' lib/opensuse_leap16.sh \
 && grep -Fq '### Managed by openSUSE Bootloader Switcher' lib/opensuse_leap16.sh; then
  pass 'fresh openSUSE Limine kernel entries no longer claim CachyOS generation'
else
  fail_test 'fresh kernel-entry generator still contains misleading CachyOS wording'
fi

tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT
cat >"$tmp/in.conf" <<'CFG'
# CachyOS Limine theme
/+openSUSE
  //6.12.0-test-a
  ### This kernel entry is generated by the openSUSE Leap adapter for CachyOS r47
  comment: kernel-version=6.12.0-test-a
  protocol: linux
  path: boot():/kernel-a

  //6.12.0-test-b
  ### This kernel entry is generated by the openSUSE Leap adapter for CachyOS r47
  comment: kernel-version=6.12.0-test-b
  protocol: linux
  path: boot():/kernel-b
CFG
(
  fail(){ printf '[fixture-fail] %s\n' "$*" >&2; }
  r24_final_fallback_block_present(){
    local conf=$1
    grep -Fqx '/EFI fallback' "$conf" \
      && grep -Fqx 'protocol: efi' "$conf" \
      && grep -Fqx 'path: boot():/EFI/BOOT/BOOTX64.EFI' "$conf"
  }
  source lib/leap16_r27.sh
  r27_render_finalized_limine_conf "$tmp/in.conf" "$tmp/out.conf" || exit 10
  [[ $(grep -Fxc '/EFI fallback' "$tmp/out.conf") == 1 ]] || exit 11
  [[ $(grep -Fc '### Managed by openSUSE Bootloader Switcher' "$tmp/out.conf") == 2 ]] || exit 12
  ! grep -Fq 'generated by the openSUSE Leap adapter for CachyOS r47' "$tmp/out.conf" || exit 13
  grep -Fqx 'path: boot():/EFI/BOOT/BOOTX64.EFI' "$tmp/out.conf" || exit 14
)
case $? in
  0) pass 'renderer adds exactly one visible EFI fallback and normalizes openSUSE kernel comments' ;;
  *) fail_test 'renderer failed finalized r23-style config upgrade fixture' ;;
esac

# Rendering an already-finalized r27 config must remain single-entry/idempotent.
cp "$tmp/out.conf" "$tmp/in2.conf"
(
  fail(){ printf '[fixture-fail] %s\n' "$*" >&2; }
  r24_final_fallback_block_present(){
    local conf=$1
    grep -Fqx '/EFI fallback' "$conf" \
      && grep -Fqx 'protocol: efi' "$conf" \
      && grep -Fqx 'path: boot():/EFI/BOOT/BOOTX64.EFI' "$conf"
  }
  source lib/leap16_r27.sh
  r27_render_finalized_limine_conf "$tmp/in2.conf" "$tmp/out2.conf" || exit 20
  cmp -s "$tmp/in2.conf" "$tmp/out2.conf" || exit 21
  [[ $(grep -Fxc '/EFI fallback' "$tmp/out2.conf") == 1 ]] || exit 22
)
case $? in
  0) pass 'renderer is idempotent once the finalized menu contract is present' ;;
  *) fail_test 'renderer duplicates or changes an already-finalized menu' ;;
esac

# The live writer must explicitly read back the installed ESP config before success.
if grep -Fq "r27_installed_menu_contract_exact \"\$conf\" || { fail 'Installed limine.conf read-back is missing the exact EFI fallback/menu-comment contract'" lib/leap16_r27.sh \
 && grep -Fq 'r21_atomic_replace "$tmp.rendered" "$conf" "$new_hash"' lib/leap16_r27.sh; then
  pass 'live writer has explicit installed-file read-back gate'
else
  fail_test 'live writer lacks the required installed-file read-back gate'
fi

if (( failures == 0 )); then
  printf 'All focused openSUSE Leap 16 r27 self-tests passed.\n'
  exit 0
fi
printf '%d focused r27 self-test(s) failed.\n' "$failures" >&2
exit 1
