#!/usr/bin/env bash
# openSUSE Leap 16 r27
#
# Finalized-Limine menu maintenance fixes:
#   * make the EFI fallback menu write self-verifying against the actual
#     /boot/efi/limine.conf installed on the ESP;
#   * keep exactly one visible /EFI fallback entry that chainloads the proven
#     standard UEFI fallback payload at EFI/BOOT/BOOTX64.EFI;
#   * remove the misleading per-kernel "for CachyOS r47" generator wording
#     from already-finalized openSUSE configurations.
#
# The hardware-proven firmware topology is intentionally untouched.

R27_MANAGED_KERNEL_COMMENT='### Managed by openSUSE Bootloader Switcher'
R27_OLD_KERNEL_COMMENT='### This kernel entry is generated by the openSUSE Leap adapter for CachyOS r47'

r27_render_finalized_limine_conf() {
    local src=$1 out=$2 fallback_count
    [[ -r $src ]] || { fail "Could not read Limine config source: $src"; return 1; }

    grep -Fq '/openSUSE GRUB2 recovery' "$src" && {
        fail 'Temporary GRUB2 recovery stanza is still present; refusing finalized-menu rewrite'
        return 1
    }

    fallback_count=$(grep -Fxc '/EFI fallback' "$src" 2>/dev/null || true)
    [[ $fallback_count =~ ^[0-9]+$ ]] || fallback_count=0
    (( fallback_count <= 1 )) || {
        fail "Limine config contains $fallback_count EFI fallback entries; refusing to guess which one is authoritative"
        return 1
    }

    if (( fallback_count == 1 )) && ! r24_final_fallback_block_present "$src"; then
        fail 'Existing EFI fallback stanza does not match the finalized Limine fallback contract'
        return 1
    fi

    awk -v old="$R27_OLD_KERNEL_COMMENT" -v new="$R27_MANAGED_KERNEL_COMMENT" '
        index($0, old) { sub(old, new); print; next }
        { print }
    ' "$src" >"$out" || return 1

    if (( fallback_count == 0 )); then
        cat >>"$out" <<'EOF_R27_FALLBACK'

/EFI fallback
### Standard UEFI fallback executable; byte-identical to canonical Limine
comment: Standard UEFI fallback loader (Limine)
protocol: efi
path: boot():/EFI/BOOT/BOOTX64.EFI
EOF_R27_FALLBACK
    fi

    return 0
}

R27_PRIMARY_ID=''
R27_FALLBACK_ID=''

r27_validate_finalized_limine_topology() {
    local ids primary_id fallback_id ph fh conf="$ESP_MOUNT/limine.conf"
    R27_PRIMARY_ID=''
    R27_FALLBACK_ID=''

    pending_exists && { fail 'An active transaction exists; refusing finalized Limine menu maintenance'; return 1; }
    detect_bootloader
    [[ $BOOTLOADER == limine ]] || { fail 'Finalized Limine menu maintenance requires a currently booted Limine installation'; return 1; }
    run_validation preflight || return 1

    ids=$(r24_current_final_ids) || return 1
    primary_id=${ids%%$'\t'*}
    fallback_id=${ids#*$'\t'}

    ph=$(r21_hash_privileged "$ESP_MOUNT/EFI/LIMINE/LIMINE_X64.EFI") || {
        fail 'Could not hash canonical Limine EFI executable'
        return 1
    }
    fh=$(r21_hash_privileged "$ESP_MOUNT/EFI/BOOT/BOOTX64.EFI") || {
        fail 'Could not hash standard EFI fallback executable'
        return 1
    }
    [[ -n $ph && $ph == "$fh" ]] || { fail 'Current EFI/BOOT fallback is not byte-identical to canonical Limine'; return 1; }

    [[ -z $(r23_current_native_grub_ids_csv) ]] || { fail 'A native openSUSE GRUB2 NVRAM alias still exists; this is not a finalized Limine-only topology'; return 1; }
    (sudo -n test ! -e "$ESP_MOUNT/EFI/OPENSUSE" 2>/dev/null || [[ ! -e $ESP_MOUNT/EFI/OPENSUSE ]]) || { fail 'EFI/OPENSUSE still exists; this is not a finalized Limine-only topology'; return 1; }
    [[ ! -e /boot/grub2 ]] || { fail '/boot/grub2 still exists; this is not a finalized Limine-only topology'; return 1; }
    [[ ! -e /etc/default/grub ]] || { fail '/etc/default/grub still exists; this is not a finalized Limine-only topology'; return 1; }
    [[ -r $conf ]] || { fail "Finalized Limine config is unreadable: $conf"; return 1; }
    grep -Fq '/openSUSE GRUB2 recovery' "$conf" && { fail 'A temporary GRUB2 recovery stanza is still present'; return 1; }

    validate_limine_boot_chain current || return 1
    R27_PRIMARY_ID=$primary_id
    R27_FALLBACK_ID=$fallback_id
    return 0
}

r27_installed_menu_contract_exact() {
    local conf=$1 fallback_count old_count
    fallback_count=$(grep -Fxc '/EFI fallback' "$conf" 2>/dev/null || true)
    old_count=$(grep -Fc "$R27_OLD_KERNEL_COMMENT" "$conf" 2>/dev/null || true)
    [[ $fallback_count == 1 ]] || return 1
    [[ $old_count == 0 ]] || return 1
    r24_final_fallback_block_present "$conf"
}

# Override the r24-r26 maintenance action.  Success is reported only after the
# exact bytes installed on the ESP have been read back and validated.
r24_add_fallback_menu_to_finalized_limine() {
    local conf="$ESP_MOUNT/limine.conf" before after tmp new_hash ids primary_id fallback_id shadow

    r27_validate_finalized_limine_topology || return 1
    primary_id=$R27_PRIMARY_ID
    fallback_id=$R27_FALLBACK_ID

    if r27_installed_menu_contract_exact "$conf"; then
        ok "Finalized Limine menu already exposes EFI fallback; firmware paths remain Boot$primary_id + Boot$fallback_id"
        return 0
    fi

    printf '\nFinalized Limine menu maintenance:\n'
    printf '  Firmware primary:  Boot%s -> \\EFI\\LIMINE\\LIMINE_X64.EFI\n' "$primary_id"
    printf '  Firmware fallback: Boot%s -> \\EFI\\BOOT\\BOOTX64.EFI\n' "$fallback_id"
    printf '  NVRAM and EFI executable payloads are not changed.\n'
    printf '  /boot/efi/limine.conf will gain one visible "EFI fallback" entry.\n'
    printf '  Existing openSUSE kernel comments will be normalized to "%s".\n' "$R27_MANAGED_KERNEL_COMMENT"
    shadow="$ESP_MOUNT/EFI/opensuse-bootloader-switcher/limine/limine.conf"
    if [[ -e $shadow ]]; then
        printf '  Informational: %s exists but is not modified by this maintenance action.\n' "$shadow"
    fi
    printf '\n'
    read -r -p 'Type APPLY to write and verify the finalized Limine menu, or anything else to cancel: ' answer
    [[ $answer == APPLY ]] || { printf '\nOperation cancelled. Nothing was modified.\n'; return 0; }

    leap16_require_sudo_session || return 1
    r27_validate_finalized_limine_topology || return 1
    primary_id=$R27_PRIMARY_ID
    fallback_id=$R27_FALLBACK_ID

    before=$(r21_hash_privileged "$conf") || { fail 'Could not hash limine.conf before maintenance'; return 1; }
    tmp=$(mktemp) || return 1
    sudo -n cat -- "$conf" >"$tmp" 2>/dev/null || cat -- "$conf" >"$tmp" || { rm -f -- "$tmp"; fail 'Could not snapshot active limine.conf'; return 1; }

    r27_render_finalized_limine_conf "$tmp" "$tmp.rendered" || { rm -f -- "$tmp" "$tmp.rendered"; return 1; }
    new_hash=$(sha256sum -- "$tmp.rendered" | awk '{print $1}')
    [[ $new_hash =~ ^[0-9A-Fa-f]{64}$ ]] || { rm -f -- "$tmp" "$tmp.rendered"; fail 'Could not hash generated Limine config'; return 1; }
    [[ $new_hash != "$before" ]] || { rm -f -- "$tmp" "$tmp.rendered"; fail 'Generated finalized Limine config did not change'; return 1; }

    r21_atomic_replace "$tmp.rendered" "$conf" "$new_hash" || { rm -f -- "$tmp" "$tmp.rendered"; return 1; }
    rm -f -- "$tmp" "$tmp.rendered"

    after=$(r21_hash_privileged "$conf") || { fail 'Could not hash installed limine.conf after maintenance'; return 1; }
    [[ $after == "$new_hash" ]] || { fail 'Installed limine.conf does not match the generated finalized menu bytes'; return 1; }
    r27_installed_menu_contract_exact "$conf" || { fail 'Installed limine.conf read-back is missing the exact EFI fallback/menu-comment contract'; return 1; }
    validate_limine_boot_chain current || { fail 'Installed finalized Limine menu failed deep validation'; return 1; }

    sudo sync -f "$conf" 2>/dev/null || sudo sync 2>/dev/null || true
    ok "Verified on-disk EFI fallback menu entry -> EFI/BOOT/BOOTX64.EFI; Boot$primary_id/Boot$fallback_id firmware topology was untouched"
    return 0
}
